services:
  # for the env vars , it's better to use MARIADB_* instead of MYSQL_* , the image supports both and this preference is for clarity purposes only
  # We used MYSQL_* here because that's the mentionned configuration in the DOM JUDGE image
  mariadb:
    # the container_name is deprecated in swarm , since swarm might be used to scale containers , and the container name must be unique
    # thus it would cause errors , so remove it and let swarm itself name the containers , while u reference them by service name or 
    # hostname
    #container_name: mariadb
    image: mariadb
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == mariadb
      restart_policy:
        condition: on-failure
    #hostname: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: domjudge
      MYSQL_USER: domjudge
      MYSQL_PASSWORD: djpw
      MYSQL_DATABASE: domjudge
    ports:
      - 13306:3306
    # many options can be passed to the mariadb for performance tuning , to see the full list visit the mariadb documentation  
    # to quickly view the list of options and default values run docker run -it --rm mariadb:latest --verbose --help (the output is huge so consider writing it into a file)
    command: --max-connections=1000 --max-allowed-packet=1024M
    # named volumes are usually better than using bind mounts for persistent storage
    volumes:
      - mariadb-data:/var/lib/mysql:rw
    networks:
      - dj_network

  domserver:
    #container_name: domserver
    image: domjudge/domserver
    #hostname: domserver
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == domserver
      restart_policy:
        condition: on-failure
    # it's better to add a condition to the depends_on (for example condition: service_healthy ) but swarm doesnt support the 
    # new compose syntax , hence you would get an error , digged through github but didn't seem to find a solution , if you found
    # a syntax or specific version of compose that would reserve the error fix it and push it pls <3
    depends_on:
      - mariadb
       #condition: service_healthy
    environment:
      MYSQL_ROOT_PASSWORD: domjudge
      MYSQL_USER: domjudge
      MYSQL_PASSWORD: djpw
      MYSQL_DATABASE: domjudge
      MYSQL_HOST: mariadb
      CONTAINER_TIMEZONE: Africa/Tunis
      DJ_DB_INSTALL_BARE: 1
    networks:
      - dj_network
    ports:
      - 12345:80


volumes:
  mariadb-data:

networks:
  dj_network:
    driver: overlay
    attachable: true 
