services:
  mariadb:
    image: mariadb
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == mariadb
      restart_policy:
        condition: any
    environment:
      MYSQL_ROOT_PASSWORD: domjudgepass
      MYSQL_USER: domjudge
      MYSQL_PASSWORD: domjudgepass
      MYSQL_DATABASE: domjudge
    ports:
      - 13306:3306
    command: --max-connections=1000 --max-allowed-packet=1024M
    volumes:
      - mariadb-data:/var/lib/mysql:rw
    networks:
      - dj_network

  domserver:
    image: domjudge/domserver
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == domserver
      restart_policy:
        condition: on-failure
    depends_on:
      - mariadb
    environment:
      MYSQL_ROOT_PASSWORD: domjudgepass
      MYSQL_USER: domjudge
      MYSQL_PASSWORD: domjudgepass
      MYSQL_DATABASE: domjudge
      MYSQL_HOST: mariadb
      CONTAINER_TIMEZONE: Africa/Tunis
      DJ_DB_INSTALL_BARE: 1
    networks:
      - dj_network
    ports:
      - 12345:80

  judgehost:
    image: "lalber/swarm-launcher"
    environment:
      LAUNCH_IMAGE: "domjudge/judgehost"
      LAUNCH_PRIVILEGED: "true"
      LAUNCH_PULL: "true"
      LAUNCH_ENVIRONMENTS: "DEAMON_ID={{.Task.Slot}} CONTAINER_TIMEZONE=Africa/Tunis DOMSERVER_BASEURL=http://domserver/ JUDGEDAEMON_USERNAME=judgehost JUDGEDAEMON_PASSWORD=uUe6xHxBezgqlB90BwQzuytSTL994S7C"
      LAUNCH_VOLUMES: "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      LAUNCH_PROJECT_NAME: "judgehost-{{.Task.Slot}}"
      LAUNCH_SERVICE_NAME: "judgehost-{{.Task.Slot}}"
      LAUNCH_CONTAINER_NAME: "judgehost-{{.Task.Slot}}"
      LAUNCH_EXT_NETWORKS: "domjudge_dj_network"
      LAUNCH_HOSTNAME: "judgehost-{{.Task.Slot}}"
    depends_on:
      - domserver
    hostname: "judgehost-{{.Task.Slot}}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
      #   delay: 60s
      replicas: 1
      placement:
        constraints:
          - node.labels.role == judgehost
    networks:
      - dj_network

volumes:
  mariadb-data:

networks:
  dj_network:
    driver: overlay
    attachable: true
