services:
  mariadb:
    container_name: mariadb
    image: docker.io/mariadb
    hostname: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
    command: --max-connections=1000 --max-allowed-packet=1024M
    volumes:
      - /var/lib/mysql
    networks:
      - domjudge

  domserver:
    container_name: domserver
    image: docker.io/domjudge/domserver
    hostname: domserver
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: mariadb
      CONTAINER_TIMEZONE: Africa/Tunis
      DJ_DB_INSTALL_BARE: 1
    networks:
      - domjudge
    ports:
      - 80:80

  # Add judgehosts here as many as you need
  judgehost-0:
    container_name: judgehost-0
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-0
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    environment:
      DAEMON_ID: 0
      JUDGEDAEMON_PASSWORD: ${JUDGEDAEMON_PASSWORD}
      CONTAINER_TIMEZONE: Africa/Tunis

  judgehost-1:
    container_name: judgehost-1
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    environment:
      DAEMON_ID: 1
      JUDGEDAEMON_PASSWORD: ${JUDGEDAEMON_PASSWORD}
      CONTAINER_TIMEZONE: Africa/Tunis

  judgehost-2:
    container_name: judgehost-2
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-2
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    environment:
      DAEMON_ID: 2
      JUDGEDAEMON_PASSWORD: ${JUDGEDAEMON_PASSWORD}
      CONTAINER_TIMEZONE: Africa/Tunis

  judgehost-3:
    container_name: judgehost-3
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-3
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    environment:
      DAEMON_ID: 3
      JUDGEDAEMON_PASSWORD: ${JUDGEDAEMON_PASSWORD}
      CONTAINER_TIMEZONE: Africa/Tunis

  judgehost-4:
    container_name: judgehost-4
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-4
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    environment:
      DAEMON_ID: 4
      JUDGEDAEMON_PASSWORD: ${JUDGEDAEMON_PASSWORD}
      CONTAINER_TIMEZONE: Africa/Tunis

  judgehost-5:
    container_name: judgehost-5
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-5
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    environment:
      DAEMON_ID: 5
      JUDGEDAEMON_PASSWORD: ${JUDGEDAEMON_PASSWORD}
      CONTAINER_TIMEZONE: Africa/Tunis

  judgehost-6:
    container_name: judgehost-6
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-6
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    environment:
      DAEMON_ID: 6
      JUDGEDAEMON_PASSWORD: ${JUDGEDAEMON_PASSWORD}
      CONTAINER_TIMEZONE: Africa/Tunis

  judgehost-7:
    container_name: judgehost-7
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-7
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    environment:
      DAEMON_ID: 7
      JUDGEDAEMON_PASSWORD: ${JUDGEDAEMON_PASSWORD}
      CONTAINER_TIMEZONE: Africa/Tunis

  judgehost-8:
    container_name: judgehost-8
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-8
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    environment:
      DAEMON_ID: 8
      JUDGEDAEMON_PASSWORD: ${JUDGEDAEMON_PASSWORD}
      CONTAINER_TIMEZONE: Africa/Tunis

  judgehost-9:
    container_name: judgehost-9
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-9
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    environment:
      DAEMON_ID: 9
      JUDGEDAEMON_PASSWORD: ${JUDGEDAEMON_PASSWORD}
      CONTAINER_TIMEZONE: Africa/Tunis

  judgehost-10:
    container_name: judgehost-10
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-10
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    environment:
      DAEMON_ID: 10
      JUDGEDAEMON_PASSWORD: ${JUDGEDAEMON_PASSWORD}
      CONTAINER_TIMEZONE: Africa/Tunis

  judgehost-11:
    container_name: judgehost-11
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-11
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    environment:
      DAEMON_ID: 11
      JUDGEDAEMON_PASSWORD: ${JUDGEDAEMON_PASSWORD}
      CONTAINER_TIMEZONE: Africa/Tunis

  judgehost-12:
    container_name: judgehost-12
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-12
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    environment:
      DAEMON_ID: 12
      JUDGEDAEMON_PASSWORD: ${JUDGEDAEMON_PASSWORD}
      CONTAINER_TIMEZONE: Africa/Tunis

  judgehost-13:
    container_name: judgehost-13
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-13
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    environment:
      DAEMON_ID: 13
      JUDGEDAEMON_PASSWORD: ${JUDGEDAEMON_PASSWORD}
      CONTAINER_TIMEZONE: Africa/Tunis

  judgehost-14:
    container_name: judgehost-14
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-14
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    environment:
      DAEMON_ID: 14
      JUDGEDAEMON_PASSWORD: ${JUDGEDAEMON_PASSWORD}
      CONTAINER_TIMEZONE: Africa/Tunis

  judgehost-15:
    container_name: judgehost-15
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-15
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    environment:
      DAEMON_ID: 15
      JUDGEDAEMON_PASSWORD: ${JUDGEDAEMON_PASSWORD}
      CONTAINER_TIMEZONE: Africa/Tunis

  judgehost-16:
    container_name: judgehost-16
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-16
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    environment:
      DAEMON_ID: 16
      JUDGEDAEMON_PASSWORD: ${JUDGEDAEMON_PASSWORD}
      CONTAINER_TIMEZONE: Africa/Tunis

networks:
  domjudge:
    driver: bridge
